config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :line_items
  resources :carts
  root "dashboard#index"
  resources :products do
    member do
      get :new_movement
      post :create_movement
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/concerns/current_cart.rb
module CurrentCart

  private

    def set_cart
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :products
  belongs_to :cart
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :product
  MovementTypes = {add: 0, remove: 1}
  validates :quantity, presence: true, numericality: true

  def self.get_movement_types
    {
      'Agregar' => MovementTypes[:add],
      'Quitar' => MovementTypes[:remove]
    }
  end

  def movement_type_name
    return "Agregar" if movement_type == MovementTypes[:add]
    return "Quitar" if movement_type == MovementTypes[:remove]
    return "NA"
  end
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :reference, presence: true
    has_many :movements
  
    def quantity
      total = 0
      self.movements.each do |movement|
        if movement.movement_type == Movement::MovementTypes[:add]
          total += movement.quantity
        else
          total -= movement.quantity
        end
      end
      return total
    end
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @products = Product.all.limit(4)
  end
  def dashboard
    @latest_movements = Movement.last(10)
    # La versión SQL y la versión Rails de la misma consulta:
    # @top_products = Product.find_by_sql("SELECT p.* FROM products p INNER JOIN movements m ON p.id = m.product_id WHERE m.movement_type = #{Movement::MovementTypes[:add]} GROUP BY p.id ORDER BY SUM(m.quantity) DESC LIMIT 10")
    #@top_products = Product.joins(:movements).where(movements: {movement_type: Movement::MovementTypes[:add]}).group(:id).order("SUM(movements.quantity) DESC").limit(10)
   
  end


end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully created." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:products_id, :cart_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="Listado de productos.xlsx"'
      }
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Se ha creado el producto correctamente.'
    else
      flash[:notice] = 'Ha ocurrido un error al crear el producto.'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=\"Listado de movimientos - #{@product.id}.xlsx\""
      }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product, notice: 'Se actualizó el producto correctamente'
    else
      render :edit
    end
  end

  def new_movement
    @product = Product.find(params[:id])
    @movement = Movement.new(product_id: @product.id)
  end
  
  def create_movement
    @product = Product.find(params[:id])
    @movement = Movement.new(movement_params)
    @movement.product_id = @product.id
    if @movement.save
      redirect_to @product, notice: 'Se creó el movimiento correctamente'
    else
      flash[:notice] = 'Ha ocurrido un error al crear el movimiento.'
      render :new_movement, status: :unprocessable_entity
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :reference)
  end

  def movement_params
    params.require(:movement).permit(:movement_type, :quantity, :comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cart %>

<div>
  <%= link_to "Edit this cart", edit_cart_path(@cart) %> |
  <%= link_to "Back to carts", carts_path %>

  <%= button_to "Destroy this cart", @cart, method: :delete %>
</div>

app/views/dashboard/index.html.erb
<div class="container px-5 my-5">
    <div class="row gx-5">
        <div class="col-lg-4 mb-5 mb-lg-0"><h1 class="fw-bolder mb-0">Bienvenidos!</h1></div>
    </div>
</div>


<!-- Features section-->
    <section class="py-5" id="features">
        <div class="container px-5 my-5">
            <div class="row gx-5">
                <div class="col-lg-4 mb-5 mb-lg-0"><h2 class="fw-bolder mb-0">Categorias</h2></div>
                <div class="col-lg-8">
                    <div class="row gx-5 row-cols-1 row-cols-md-2">
                        <div class="col mb-5 h-100">
                            <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i></div>
                            <h2 class="h5">Sellantes - Fijación y Tornillería</h2>
                            <p class="mb-0">Accesorios para fijación, protectores de madera, sellantes, tornillos, pernos, tuercas, entre otros.</p>
                        </div>
                        <div class="col mb-5 h-100">
                            <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-building"></i></div>
                            <h2 class="h5">Ferreteria</h2>
                            <p class="mb-0">Todo lo relacionado al ramo ferretero, herramientas, repuestos, consumibles.</p>
                        </div>
                        <div class="col mb-5 mb-md-0 h-100">
                            <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-toggles2"></i></div>
                            <h2 class="h5">Pinturas y Complementos</h2>
                            <p class="mb-0">Pinturas para interior y exterior, pintura en bolsa, madera, metales, barniz, spray.</p>
                        </div>
                        <div class="col h-100">
                            <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-toggles2"></i></div>
                            <h2 class="h5">Herramientas electricas</h2>
                            <p class="mb-0">Taladros, taladros inhalambricos, esmeril angular, lijadora orbital, cepillo de madera, fresadora tupi.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
       
   
   
    <!-- Call to action-->
          
    <div class="row">
    <div class="col-md-8 offset-2">
        <div class="container">
            <div class="row">
                <% @products.each do |product| %> <!--Con esto trae todos los productos a la vista-->
                    <div class="col-md-3 mb-3"> <!--Cn esto se crea las tarjetas-->
                        <div class="card">
                            <img class="card-img-top" src="https://dummyimage.com/600x400/c7c7c7/737373&text=image" alt="<%=product.name%>" />
                            <div class="card-block">
                                <h5 class="card-title">
                                    <%= product.name %>
                                </h5>
                                <div class="card-text">
                                    <div class="badge badge-primary text-black">
                                   
                                    </div>
                                    <div>$<%= product.reference %>
                                    </div>
                                </div>
                                <div class="row float-right">
                                    <div class="col-md-12">
                                       
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<!-- Call to action-->

    <aside class="bg-primary bg-gradient rounded-3 p-4 p-sm-5 mt-5">
        <div class="d-flex align-items-center justify-content-between flex-column flex-xl-row text-center text-xl-start">
        
        
        <!-- Testimonial section-->
        
            <div class="container px-5 my-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-10 col-xl-7">
                        <div class="text-center">
                            <div class="fs-4 mb-4 fst-italic">"Innovamos para apoyar tus proyectos de restauración, remodelación y construcción"</div>
                            <div class="d-flex align-items-center justify-content-center">
                                <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />
                                <div class="fw-bold">
                                    
                                    <span class="fw-bold text-primary mx-1">/</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
        
                
        </div>
    </aside>
    </div>
    </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tuferrexpress</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />


    </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


  <%= render "shared/navbar" %>
  <%= render "shared/header" %>

  <%= yield %>

  <%= render "shared/footer" %>




<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>



  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :products_id, style: "display: block" %>
    <%= form.text_field :products_id %>
  </div>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<div id="<%= dom_id line_item %>">
  <p>
    <strong>Products:</strong>
    <%= line_item.products_id %>
  </p>

  <p>
    <strong>Cart:</strong>
    <%= line_item.cart_id %>
  </p>

</div>

app/views/line_items/edit.html.erb
<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show this line item", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New line item", new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @line_item %>

<div>
  <%= link_to "Edit this line item", edit_line_item_path(@line_item) %> |
  <%= link_to "Back to line items", line_items_path %>

  <%= button_to "Destroy this line item", @line_item, method: :delete %>
</div>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      
        <%= form_with(model: product) do |form| %>
          <% if product.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
        
              <ul>
                <% product.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :name, style: "display: block" %>
            <%= form.text_field :name, class:'form-control', placeholder: 'Nombre' %>
          </div>

          <div class="form-group">
            <%= form.label :reference, style: "display: block" %>
            <%= form.text_field :reference, class:'form-control', placeholder: 'Codigo de referencia SKU' %>
          </div>

          <div class="form-group">
            <%= form.label :brand, style: "display: block" %>
            <%= form.text_field :brand, class:'form-control', placeholder: 'Marca' %> 
          </div>

          <div class="form-group">
            <%= form.label :description, style: "display: block" %>
            <%= form.text_area :description, class:'form-control', placeholder: 'Descripción' %>
          </div>
                <br><br>    
          <div>
            <%= form.submit "Enviar", class:'btn btn-primary'%>
          </div>
      <% end %>
    </div>
  </div>
 
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Reference:</strong>
    <%= product.reference %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= product.brand %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editar producto</h1>

<%= render "form", product: @product %>

<div>
  <%= link_to "Mostrar producto", @product, class:'btn btn-primary' %> 
   <%= link_to "Volver a productos", products_path, class:'btn btn-primary' %>
</div>

app/views/products/index.html.erb
<h1>Listado de productos</h1>
<a href="<%= new_product_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
  </span>
  <span class="text">Crear Producto</span>
</a>
<a href="<%= products_path(format: :xlsx) %>" class="btn btn-success btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-file"></i>
  </span>
  <span class="text">Exportar a Excel</span>
</a>
<br><br>
<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Referencia</th>
      <th>Cantidad</th>
      <th>Acciones</th>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td><%= product.reference %></td>
      <td><%= product.quantity %></td>
      <td><%= link_to "Detalles", product_path(product), class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Crear producto</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Volver a productos", products_path, class:'btn btn-primary' %>
</div>

app/views/products/new_movement.html.erb
<h1>Crear movimiento</h1>
<div class = "row">
    <div class = "col-lg-12">
        <div class = "card">
            <table class = "table">
                <tr>
                    <td><b>Nombre:</b></td>
                    <td><%= @product.name %></td>
                </tr>    
                <tr>
                    <td><b>Referencia:</b></td>
                    <td><%= @product.reference %></td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div class = "row mt-5">
    <div class = "col-lg-12">
        <div class = "card p-5">
            <%= form_with model: @movement, url: create_movement_product_path(@product) do |f| %>

                <% if @movement.errors.any? %>
                  <div class="alert alert-danger">
                    <h3><% flash [:notice] %></h3>
                    <ul>
                        <% @movement.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                  </div>
                <% end %>
            
            <div class="form-group">
                <%= f.label :movement_type, "Tipo de movimiento" %>
                <%= f.select :movement_type, options_for_select(Movement.get_movement_types),{}, {class:'form-control'} %>
            </div>

            <div class = "form-group">
                <%= f.label :quantity, "Cantidad" %>
                <%= f.number_field :quantity, {class: 'form-control'} %>
            </div>

            <div class = "form-group">
                <%= f.label :comment, "Comentario" %>
                <%= f.text_area :comment, class: 'form-control' %>
            </div>
            <div class = "form-group">
                <%= f.submit 'Crear movimiento', class: 'btn btn-primary' %>
                <%= link_to 'Cancelar', product_path(@product), class: 'btn btn-danger' %>
            </div>
        <%end%>
    </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles del producto</h1>
    <%= link_to "Regresar al listado de productos", products_path, class: 'btn btn-primary' %>
    <%= link_to "Editar", edit_product_path(@product), class: 'btn btn-primary' %>
    <%= link_to "Crear movimiento", new_movement_product_path(@product), class: 'btn btn-primary' %>
    <%= link_to "Descargar movimientos", product_path(@product, format: :xlsx), class: 'btn btn-success' %>
    <div class="card" style="padding: 20px;">
      <table class="table">
        <tr>
          <td><b>Nombre del producto:</b></td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td><b>Referencia:</b></td>
          <td><%= @product.reference %></td>
        </tr>
        <tr>
          <td><b>Cantidad actual:</b></td>
          <td><%= @product.quantity %></td>
        </tr>
        <tr>
          <td><b>Descripción:</b></td>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <td><b>Fecha de creación:</b></td>
          <td><%= @product.created_at %></td>
        </tr>
        <tr>
          <td><b>Fecha de actualización:</b></td>
          <td><%= @product.updated_at %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<br>
<div class="row" style="margin-top: 20px">
  <div class="col-lg-12">
    <div class="card" style="padding: 20px; ">
      <h1>Movimientos</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Tipo</th>
            <th>Cantidad</th>
            <th>Comentario</th>
            <th>Fecha</th>
          </tr>
        </thead>
        <tbody>
          <% @product.movements.each do |movement| %>
          <tr>
            <td><%= movement.movement_type_name %></td>
            <td><%= movement.quantity %></td>
            <td><%= movement.comment %></td>
            <td><%= movement.created_at %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shared/_card_product.html.erb
<div class="card" style="width: 80%;">
  
  <div class="card-body">
    <h4 class="card-title"><%= product.name %></h4>
    <p class="card-text">
        <%= product.description %>
    </p>
    <p class="text-secondary">
      <i class="bi bi-person-check-fill"></i>
      <%= product.name %>
    </p>
  </div>
</div>

<%= link_to "New product", new_product_path %>

app/views/shared/_footer.html.erb
<!-- Footer-->
<footer class="bg-dark py-4 mt-auto">
    <div class="container px-5">
        <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; Tuferrexpress 2022</div></div>
            <div class="col-auto">
                <a class="link-light small" href="#!">Contactanos</a>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="#!">Whatssap +56965306983</a>
         
               
            </div>
        </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-5">
            <div class="row gx-5 align-items-center justify-content-center">
                <div class="col-lg-8 col-xl-7 col-xxl-6">
                    <div class="my-5 text-center text-xl-start">
                        <h1 class="display-5 fw-bolder text-white mb-2">Tuferrexpress</h1>
                        <p class="lead fw-normal text-white-50 mb-4">La ferreteria cercana al vecino!</p>
                        
                    </div>
                </div>
                
                <div class="col-xl-5 col-xxl-6 d-noned-xl-block">
                <%= image_tag 'logocircular2.png', id: 'logo', size:'120x120', class: 'img-responsive class="img-responsive ml-auto d-block mx-auto' %>
                </div>
                
                 
            </div>
        </div>
    </header>

app/views/shared/_navbar.html.erb
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="index.html">

        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">


                <li class="nav-item"><a class="nav-link" href="<%= root_path %>">Inicio</a></li>
                <li class="nav-item"><a class="nav-link" href="<%= products_path %>">Productos</a></li>
            </ul>
        </div>
    </div>
</nav>